name: truck_booking_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For making HTTP requests
  http: ^1.2.1 

  # For simple state management
  provider: ^6.1.2 

  # For formatting dates and times
  intl: ^0.19.0

  # (Optional, but recommended for production to securely store tokens)
  # flutter_secure_storage: ^9.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true