// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYpnfe9gts9hYEVr3R9kNNv4XOqcnNZdg',
    appId: '1:245653745365:web:5106912438d883130cbc5c',
    messagingSenderId: '245653745365',
    projectId: 'thruckbooking',
    authDomain: 'thruckbooking.firebaseapp.com',
    storageBucket: 'thruckbooking.firebasestorage.app',
    measurementId: 'G-B6860DVMCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTmwMh9-PoeZgkp_s_NhOB6kYcY57ipdE',
    appId: '1:245653745365:android:2be72f539404e26a0cbc5c',
    messagingSenderId: '245653745365',
    projectId: 'thruckbooking',
    storageBucket: 'thruckbooking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-r3gmY8fwyz3sP2Oh4SKFHC6jz2-mAY',
    appId: '1:245653745365:ios:c178c166e23478410cbc5c',
    messagingSenderId: '245653745365',
    projectId: 'thruckbooking',
    storageBucket: 'thruckbooking.firebasestorage.app',
    iosBundleId: 'com.example.mock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-r3gmY8fwyz3sP2Oh4SKFHC6jz2-mAY',
    appId: '1:245653745365:ios:c178c166e23478410cbc5c',
    messagingSenderId: '245653745365',
    projectId: 'thruckbooking',
    storageBucket: 'thruckbooking.firebasestorage.app',
    iosBundleId: 'com.example.mock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYpnfe9gts9hYEVr3R9kNNv4XOqcnNZdg',
    appId: '1:245653745365:web:59cba00ee615eb4d0cbc5c',
    messagingSenderId: '245653745365',
    projectId: 'thruckbooking',
    authDomain: 'thruckbooking.firebaseapp.com',
    storageBucket: 'thruckbooking.firebasestorage.app',
    measurementId: 'G-QDDX57GDF1',
  );
}
